version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mcca
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile

    ports:
      - 8303:80
    volumes:
      - ./src:/var/www/html

volumes:
  db_data:
