version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mcca
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile

    ports:
      - 8303:80
    volumes:
      - ./src:/var/www/html
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - 8304:80
    depends_on:
      - db
volumes:
  db_data:
